[package]
name = "progress_server"
version = "0.1.0"
authors = ["Jonathan McElroy <jonathanpmcelroy@gmail.com>"]

[dependencies]
nickel = "*"
rustc-serialize = "*"
rust-ini = "*"
regex = "*"
url = "*"
docopt = "*"
nom = "*"

[dependencies.hyper]
version = "*"
default-features = false
